version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecoreboot
    volumes:
      - db_data:/var/lib/mysql
      - ./ecoreboot.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  # Añade esto en docker-compose.yml
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  db_data: