version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Ecoreboot:/var/www/html/Ecoreboot
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecoreboot
    volumes:
      - db_data:/var/lib/mysql
      - ./ecoreboot.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  # Añade esto en docker-compose.yml
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: ecoreboot_swagger
    ports:
      - "8082:8080"
    volumes:
      # Mapear la carpeta local 'Api' a una carpeta dentro del contenedor
      - ./Api:/usr/share/nginx/html/Api
    environment:
      # Indica la ruta interna donde Swagger UI buscará tu swagger.json
      # ¡Ojo con mayúsculas y minúsculas!
      SWAGGER_JSON: /swagger.yaml
    depends_on:
      - web


volumes:
  db_data: