version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecoreboot
    volumes:
      - db_data:/var/lib/mysql
      - ./ecoreboot.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"  # Mapea el puerto 8000
    environment:
      - DB_HOST=db  # Nombre del servicio MySQL
      - DB_USER=root
      - DB_PASSWORD=  # Contraseña vacía según tu configuración
      - DB_NAME=ecoreboot
    depends_on:
      - db  # Espera a que la base de datos esté lista


volumes:
  db_data: